### ISSUE TITLE
[firefox] QuotaExceededError: storage.sync API call exceeded its quota limitations

### ISSUE THREAD

**Issue by Horonelius** [zoomerdev/dbased#10]
Ever since the latest version went live, I have been unable to either add new stickers to the plugin, or remove old ones. Uninstalling the plugin also does not wipe the sticker cache for the plugin, so attempting to reinstall to fix it just gives me the old stickers back.

Latest version of Firefox, version 79.0

**Comment by zoomerdev** [comment]
can you try typing `localStorage.clear()` in F12 menu while you're on the dlive page? then try a refresh and maybe uninstall/reinstall the addon. If the problem persists lmk

**Comment by Horonelius** [comment]
All that seems to have done is force me to log back into Dlive. After refreshing, the stickers are back with the same original issue.

**Comment by Horonelius** [comment]
Sounds like Mozilla made a change to storage.sync on the 27th according to https://blog.mozilla.org/addons/2020/07/09/changes-to-storage-sync-in-firefox-79/comment-page-1/

**Comment by zoomerdev** [comment]
oh ok that's it then. ugh, i will need to workaround the storage limits.

**Comment by Horonelius** [comment]
While waiting for the fix in the meantime, I was able to set _webextensions.storage.sync.kinto_ to _true_ temporarily to clean out a few extra stickers to get myself under the limit, and the extension functions normally again.

**Comment by zweibol** [comment]
I'm guessing this is why I can't add more than 255 stickers? storage.sync limitations as opposed localstorage. 😢

**Comment by zoomerdev** [comment]
available in release `1.1.1`
