### ISSUE TITLE
Stickers appearing huge in emote menu

### ISSUE THREAD

**Issue by Horonelius** [zoomerdev/dbased#8]
Dlive decided to rework their chat interface, and with the addition of emotes, the extensions stickers now appear under the emote window, and are MASSIVE, the width of the chat window. They need to be relocated to the sticker tab.

**Comment by Horonelius** [comment]
Nevermind...

**Comment by zoomerdev** [comment]
fixed in https://github.com/zoomerdev/dbased/commit/300219813a8a625fa95d33995fe3a9efa9c2ba2d
